cluster.name: elk-cluster
node.name: es-node
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

discovery.type: single-node
#discovery.seed_hosts: ["localhost"]
#cluster.initial_master_nodes: ["es-node"]

xpack.security.enabled: true
xpack.security.enrollment.enabled: false

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.http.ssl.verification_mode: certificate

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.transport.ssl.verification_mode: certificate

bootstrap.memory_lock: true
action.auto_create_index: .monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*,*
