version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=ChangeMe123!
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      #- ELASTIC_PASSWORD=${ELASTIC_PASSWORD} | docker exec -it elk-elasticsearch /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto --batch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./cert:/usr/share/elasticsearch/config/certs:ro
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k -u elastic:ChangeMe123! https://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk-net

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.2
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_USER=logstash_internal
      - ELASTICSEARCH_PASSWORD=ChangeMe123!
      - LOGSTASH_SYSTEM_PASSWORD=ChangeMe123!
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./cert:/usr/share/logstash/config/certs:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5044:5044
    restart: unless-stopped
    networks:
      - elk-net
    depends_on:
      elasticsearch: 
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.2
    container_name: kibana
    environment:
      - KIBANA_SYSTEM_PASSWORD=ChangeMe123!
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./cert:/usr/share/kibana/config/certs:ro
    ports:
      - 5601:5601
    restart: unless-stopped
    networks:
      - elk-net
    depends_on:
      elasticsearch:
        condition: service_healthy
networks:
  elk-net:
    driver: bridge
