server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}

server.ssl.enabled: true
server.ssl.keystore.path: /usr/share/kibana/config/certs/elastic-certificates.p12
server.ssl.keystore.password: ""

#elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/elastic-certificates.crt"]
#elasticsearch.ssl.verificationMode: certificate

elasticsearch.ssl.verificationMode: none
xpack.security.encryptionKey: "A_Very_Long_Random_String_32chars_min"
xpack.encryptedSavedObjects.encryptionKey: "Another_Long_Random_String_32chars_min"
xpack.reporting.encryptionKey: "Yet_Another_Long_Random_String_32chars_min"

xpack.monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: "zh-CN"
