node.name: logstash
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
pipeline.batch.size: 125
pipeline.batch.delay: 50

xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch:9200"]
xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/certs/elastic-ca.crt
xpack.monitoring.elasticsearch.ssl.verification_mode: certificate
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: ${LOGSTASH_SYSTEM_PASSWORD}
